### Anthony Rodrigues
#### RollNo. 58
#### SE-AIML
#### Date: 16/02/2026

# Experiment 5: Disease Prediction using Naive Bayes and Neural Network with Comparison of Classifiers

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier   
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score,recall_score,f1_score,roc_auc_score,classification_report

#### Load the dataset

In [5]:
data=load_breast_cancer()
X=data.data
y=data.target
print("Classes:",data.target_names)

Classes: ['malignant' 'benign']


In [6]:
df = pd.DataFrame(data.data, columns=data.feature_names)
df["target"] = data.target

In [7]:
print(df.shape)

(569, 31)


In [8]:
print(df.head())

   mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0             

In [9]:
print(df.tail())

     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  wo

In [10]:
print("\nDataset Info:")
print(df.info())


Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness 

In [11]:
print("\ndescribe:")
print(df.describe())


describe:
       mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000  

#### Split data

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

## Table A

#### Logistic Regression

In [13]:
lr=LogisticRegression(max_iter=5000)
lr.fit(X_train,y_train)
pred_lr=lr.predict(X_test)
print("Logistic Test Accuracy:",accuracy_score(y_test,pred_lr))
pred_lr_train=lr.predict(X_train)
print("Logistic Train Accuracy:",accuracy_score(y_train,pred_lr_train))

Logistic Test Accuracy: 0.9707602339181286
Logistic Train Accuracy: 0.964824120603015


#### Decision Tree

In [14]:
dt=DecisionTreeClassifier()
dt.fit(X_train,y_train)
pred_dt=dt.predict(X_test)
print("Logistic Test Accuracy:",accuracy_score(y_test,pred_dt))
pred_dt_train=dt.predict(X_train)
print("Logistic Train Accuracy:",accuracy_score(y_train,pred_dt_train))

Logistic Test Accuracy: 0.935672514619883
Logistic Train Accuracy: 1.0


#### KNN

In [15]:
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)
pred_knn=knn.predict(X_test)
print("Logistic Test Accuracy:",accuracy_score(y_test,pred_knn))
pred_knn_train=knn.predict(X_train)
print("Logistic Train Accuracy:",accuracy_score(y_train,pred_knn_train))

Logistic Test Accuracy: 0.9473684210526315
Logistic Train Accuracy: 0.9396984924623115


#### Naive Bayes

In [16]:
nb=GaussianNB()
nb.fit(X_train,y_train)
pred_nb=nb.predict(X_test)
print("Logistic Test Accuracy:",accuracy_score(y_test,pred_nb))
pred_nb_train=nb.predict(X_train)
print("Logistic Train Accuracy:",accuracy_score(y_train,pred_nb_train))

Logistic Test Accuracy: 0.9532163742690059
Logistic Train Accuracy: 0.9422110552763819


#### Neural Network

In [17]:
nn=MLPClassifier(max_iter=5000)
nn.fit(X_train,y_train)
pred_nn=nn.predict(X_test)
print("Logistic Test Accuracy:",accuracy_score(y_test,pred_nn))
pred_nn_train=nn.predict(X_train)
print("Logistic Train Accuracy:",accuracy_score(y_train,pred_nn_train))

Logistic Test Accuracy: 0.9532163742690059
Logistic Train Accuracy: 0.9522613065326633


## Table B

#### Logistic Regression

In [18]:
cm_lr=confusion_matrix(y_test,pred_lr)
print("\nLogistic Regression Confusion Matrix:")
print(cm_lr)

TN1, FP1, FN1, TP1 = cm_lr.ravel()
type1_lr=FP1/(FP1+TN1)
type2_lr=FN1/(FN1+TP1)

print("FP Type1:",FP1)
print("FN Type2:",FN1)
print("Type1 Error rate:",type1_lr*100)
print("Type2 Error rate: ",type2_lr*100)


Logistic Regression Confusion Matrix:
[[ 60   4]
 [  1 106]]
FP Type1: 4
FN Type2: 1
Type1 Error rate: 6.25
Type2 Error rate:  0.9345794392523363


#### Decision Tree

In [19]:
cm_dt=confusion_matrix(y_test,pred_dt)
print("\nDecision tree Confusion Matrix:")
print(cm_dt)

TN2, FP2, FN2, TP2 = cm_dt.ravel()
type1_dt=FP2/(FP2+TN2)
type2_dt=FN2/(FN2+TP2)

print("FP Type1:",FP2)
print("FN Type2:",FN2)
print("Type1 Error rate:",type1_dt*100)
print("Type2 Error rate: ",type2_dt*100)


Decision tree Confusion Matrix:
[[ 57   7]
 [  4 103]]
FP Type1: 7
FN Type2: 4
Type1 Error rate: 10.9375
Type2 Error rate:  3.7383177570093453


#### KNN

In [20]:
cm_knn=confusion_matrix(y_test,pred_knn)
print("\nKNN Confusion Matrix:")
print(cm_knn)

TN3, FP3, FN3, TP3 = cm_knn.ravel()
type1_knn=FP3/(FP3+TN3)
type2_knn=FN3/(FN3+TP3)

print("FP Type1:",FP3)
print("FN Type2:",FN3)
print("Type1 Error rate:",type1_knn*100)
print("Type2 Error rate: ",type2_knn*100)


KNN Confusion Matrix:
[[ 58   6]
 [  3 104]]
FP Type1: 6
FN Type2: 3
Type1 Error rate: 9.375
Type2 Error rate:  2.803738317757009


#### Naive Bayes

In [21]:
cm_nb=confusion_matrix(y_test,pred_nb)
print("\nNaive Bayes Confusion Matrix:")
print(cm_nb)

TN4, FP4, FN4, TP4 = cm_nb.ravel()
type1_nb=FP4/(FP4+TN4)
type2_nb=FN4/(FN4+TP4)

print("FP Type1:",FP4)
print("FN Type2:",FN4)
print("Type1 Error rate:",type1_nb*100)
print("Type2 Error rate: ",type2_nb*100)


Naive Bayes Confusion Matrix:
[[ 58   6]
 [  2 105]]
FP Type1: 6
FN Type2: 2
Type1 Error rate: 9.375
Type2 Error rate:  1.8691588785046727


#### Neural Network

In [22]:
cm_nn=confusion_matrix(y_test,pred_nn)
print("\nNeural Network Confusion Matrix:")
print(cm_nn)

TN5, FP5, FN5, TP5 = cm_nn.ravel()
type1_nn=FP5/(FP5+TN5)
type2_nn=FN5/(FN5+TP5)

print("FP Type1:",FP5)
print("FN Type2:",FN5)
print("Type1 Error rate:",type1_nn*100)
print("Type2 Error rate: ",type2_nn*100)


Neural Network Confusion Matrix:
[[ 57   7]
 [  1 106]]
FP Type1: 7
FN Type2: 1
Type1 Error rate: 10.9375
Type2 Error rate:  0.9345794392523363


## Table C

#### Logistic Regression

In [28]:
precision2= precision_score(y_test, pred_lr)
recall2= recall_score(y_test, pred_lr)
f12= f1_score(y_test, pred_lr)
roc2 = roc_auc_score(y_test, pred_lr)

print("Precision :", precision2)
print("Recall:", recall2)
print("Fi-score :", f12)
print("ROC-AUC:", roc2)

Precision : 0.9636363636363636
Recall: 0.9906542056074766
Fi-score : 0.9769585253456221
ROC-AUC: 0.9640771028037383


#### Decision Tree

In [29]:
precision1= precision_score(y_test, pred_dt)
recall1= recall_score(y_test, pred_dt)
f11= f1_score(y_test, pred_dt)
roc1 = roc_auc_score(y_test, pred_dt)

print("Precision :", precision1)
print("Recall:", recall1)
print("Fi-score :", f11)
print("ROC-AUC:", roc1)

Precision : 0.9363636363636364
Recall: 0.9626168224299065
Fi-score : 0.9493087557603687
ROC-AUC: 0.9266209112149533


#### KNN

In [30]:
precision3= precision_score(y_test, pred_knn)
recall3= recall_score(y_test, pred_knn)
f13= f1_score(y_test, pred_knn)
roc3 = roc_auc_score(y_test, pred_knn)

print("Precision :", precision3)
print("Recall:", recall3)
print("Fi-score :", f13)
print("ROC-AUC:", roc3)

Precision : 0.9454545454545454
Recall: 0.9719626168224299
Fi-score : 0.9585253456221198
ROC-AUC: 0.939106308411215


#### Naive Bayes

In [31]:
precision4= precision_score(y_test, pred_nb)
recall4= recall_score(y_test, pred_nn)
f14= f1_score(y_test, pred_nn)
roc4 = roc_auc_score(y_test, pred_nn)

print("Precision :", precision4)
print("Recall:", recall4)
print("Fi-score :", f14)
print("ROC-AUC:", roc4)

Precision : 0.9459459459459459
Recall: 0.9906542056074766
Fi-score : 0.9636363636363636
ROC-AUC: 0.9406396028037383


#### Neural Network

In [32]:
precision5= precision_score(y_test, pred_nn)
recall5= recall_score(y_test, pred_nn)
f15= f1_score(y_test, pred_nn)
roc5 = roc_auc_score(y_test, pred_nn)

print("Precision :", precision5)
print("Recall:", recall5)
print("Fi-score :", f15)
print("ROC-AUC:", roc5)

Precision : 0.9380530973451328
Recall: 0.9906542056074766
Fi-score : 0.9636363636363636
ROC-AUC: 0.9406396028037383
